### ISSUE TITLE
BAT not working

### ISSUE THREAD

**Issue by ch570512** [MiSTer-devel/Arcade-Sprint2_MiSTer#1]
Path/File not found.

**Comment by alanswx** [comment]
Are you using the non merged zip? I just used one from 203 and it worked. Do you have 7za in your path?

**Comment by ch570512** [comment]
Seems I can't find the correct ROM. Mine has only 6404.d1 and 6405.e1 in it the Zip.

**Comment by alanswx** [comment]
<pre>
Archive:  sprint2.zip
TORRENTZIPPED-5CC6114B
  Length      Date    Time    Name
---------  ---------- -----   ----
     2048  1996-12-24 23:32   6290-01.b1
     2048  1996-12-24 23:32   6291-01.c1
      512  1996-12-24 23:32   6396-01.p4
      512  1996-12-24 23:32   6397-01.r4
      512  1996-12-24 23:32   6398-01.k6
      512  1996-12-24 23:32   6399-01.j6
      256  1996-12-24 23:32   6400-01.m2
       32  1996-12-24 23:32   6401-01.e2
     2048  1996-12-24 23:32   6404.d1
     2048  1996-12-24 23:32   6405.e1
---------                     -------
    10528                     10 files
</pre>
MAME 203

**Comment by alanswx** [comment]
Do you have the merged sprint1.zip instead of the non-merged sprint2.zip?
<pre>
Archive:  MAME 0.203 ROMs (merged)/sprint1.zip
TORRENTZIPPED-96E38BE9
  Length      Date    Time    Name
---------  ---------- -----   ----
     2048  1996-12-24 23:32   6290-01.b1
     2048  1996-12-24 23:32   6291-01.c1
      512  1996-12-24 23:32   6396-01.p4
      512  1996-12-24 23:32   6397-01.r4
      512  1996-12-24 23:32   6398-01.k6
      512  1996-12-24 23:32   6399-01.j6
      256  1996-12-24 23:32   6400-01.m2
       32  1996-12-24 23:32   6401-01.e2
     2048  1996-12-24 23:32   6442-01.d1
     2048  1996-12-24 23:32   6443-01.e1
     2048  1996-12-24 23:32   sprint2/6404.d1
     2048  1996-12-24 23:32   sprint2/6405.e1
     2048  1996-12-24 23:32   sprint2a/6405-02.e1
     2048  1996-12-24 23:32   sprint2h/6405-02.e1
---------                     -------
    18720                     14 files
</pre>

**Comment by ch570512** [comment]
Hi Alan - thanks for your help. I copied the missing files from sprint1.zip (8 files) to my sprint2.zip (2 files) and got a working sprint2.zip (10 Files).

**Comment by alanswx** [comment]
Great news!
